export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const RESEND_VERIFY_OTP_SUCCESS = 'RESEND_VERIFY_OTP_SUCCESS'
export const VERIFY_DETAILS_SUCCESS = 'VERIFY_DETAILS_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const START_LOADER = 'START_LOADER';
export const START_OTHER_LOADER = 'START_OTHER_LOADER'
export const STOP_LOADER = 'STOP_LOADER';
export const STOP_OTHER_LOADER = 'STOP_OTHER_LOADER'
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';

export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const SET_PASSWORD_SUCCESS = 'SET_PASSWORD_SUCCESS';
export const VERIFY_CODE_SUCCESS = 'VERIFY_CODE_SUCCESS'

export const RESEND_OTP_FORGOT_PASSWORD = 'RESEND_OTP_FORGOT_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const VERIFY_RESET_PASSWORD_LINK_SUCCESS = 'VERIFY_RESET_PASSWORD_LINK_SUCCESS';

export const SUBSCRIBE_USER_SUCCESS = 'SUBSCRIBE_USER_SUCCESS';

export const GET_DASHBOARD_USERS_SUCCESS = 'GET_DASHBOARD_USERS_SUCCESS';
export const GET_REVIEW_SUCCESS = 'GET_REVIEW_SUCCESS';
export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS';
export const READ_NOTIFICATION_SUCCESS = 'READ_NOTIFICATION_SUCCESS';

export const GET_DASHBOARD_APPOINTMENTS_SUCCESS = 'GET_DASHBOARD_APPOINTMENTS_SUCCESS';

export const GET_UPCOMING_APPOINTMENT_SUCCESS = 'GET_UPCOMING_APPOINTMENT_SUCCESS'
export const ORDER_CANCEL_STATUS_SUCCESS = 'ORDER_CANCEL_STATUS_SUCCESS'
export const ORDER_MISS_STATUS_SUCCESS = 'ORDER_MISS_STATUS_SUCCESS'
export const ADD_APPOINTMENT = 'ADD_APPOINTMENT'

export const GET_SALONS_SUCCESS = 'GET_SALONS_SUCCESS';
export const BLOCK_UNBLOCK_SALONS_SUCCESS = 'BLOCK_UNBLOCK_SALONS_SUCCESS';
export const DELETE_SALONS_SUCCESS = 'DELETE_SALONS_SUCCESS';
export const VERIFY_SALONS_SUCCESS = 'VERIFY_SALONS_SUCCESS';

export const GET_SALON_REVIEWS_SUCCESS = 'GET_SALON_REVIEWS_SUCCESS';
export const CONTACT_US_SUCCESS = 'CONTACT_US_SUCCESS';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const DELETE_SALON_REVIEWS_SUCCESS = 'DELETE_SALON_REVIEWS_SUCCESS';
export const GET_EARNINGS_SUCCESS = 'GET_EARNINGS_SUCCESS';
export const GET_PORTFOLIO_SUCCESS = 'GET_PORTFOLIO_SUCCESS';
export const SALON_PORTFOLIO_SUCCESS = 'SALON_PORTFOLIO_SUCCESS';
export const DELETE_SALON_PORTFOLIO_SUCCESS = 'DELETE_SALON_PORTFOLIO_SUCCESS';
export const GET_BUSINESS_HOURS_SUCCESS = 'GET_BUSINESS_HOURS_SUCCESS';
export const GET_DAILY_BUSINESS_HOURS_SUCCESS = 'GET_DAILY_BUSINESS_HOURS_SUCCESS';
export const UPDATE_DAILY_BUSINESS_HOURS_SUCCESS = 'UPDATE_DAILY_BUSINESS_HOURS_SUCCESS'
export const EDIT_BUSINESS_HOURS_SUCCESS = 'EDIT_BUSINESS_HOURS_SUCCESS';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';
export const GET_APPOINTMENT_SUCCESS = 'GET_APPOINTMENT_SUCCESS';
export const EDIT_SALON_PROFILE = 'EDIT_SALON_PROFILE';
export const GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS';
export const GET_FREESLOTS_SUCCESS = 'GET_FREESLOTS_SUCCESS'
export const EDIT_SERVICES_SUCCESS = 'EDIT_SERVICES_SUCCESS';
export const DELETE_SERVICES_SUCCESS = 'DELETE_SERVICES_SUCCESS';
export const ADD_SERVICES_SUCCESS = 'ADD_SERVICES_SUCCESS';

export const GET_SERVICE_CATEGORY = 'GET_SERVICE_CATEGORY';
export const ADD_SERVICE_CATEGORY = 'ADD_SERVICE_CATEGORY';
export const EDIT_SERVICE_CATEGORY = 'EDIT_SERVICE_CATEGORY';
export const DELETE_SERVICE_CATEGORY = 'DELETE_SERVICE_CATEGORY';

export const GET_BARBERS_SUCCESS = 'GET_BARBERS_SUCCESS';
export const ADD_BARBERS_SUCCESS = 'ADD_BARBERS_SUCCESS';
export const DELETE_BARBERS_SUCCESS = 'DELETE_BARBERS_SUCCESS';
export const MANAGE_BARBERS_SUCCESS = 'MANAGE_BARBERS_SUCCESS';
export const MANAGE_BARBERS_FAILURE = 'MANAGE_BARBERS_FAILURE';
export const EDIT_BARBER_SUCCESS = 'EDIT_BARBER_SUCCESS';

export const GET_BARBER_BUSINESS_HOURS_SUCCESS = 'GET_BARBER_BUSINESS_HOURS_SUCCESS';
export const EDIT_BARBER_BUSINESS_HOURS_SUCCESS = 'EDIT_BARBER_BUSINESS_HOURS_SUCCESS';

export const GET_BARBER_BUSINESS_EXCEPTION_HOURS = 'GET_BARBER_BUSINESS_EXCEPTION_HOURS';
export const UPDATE_BARBER_BUSINESS_EXCEPTION_HOURS = 'UPDATE_BARBER_BUSINESS_EXCEPTION_HOURS'

export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const ADD_CUSTOMERS = 'ADD_CUSTOMERS';
export const EDIT_CUSTOMERS = 'EDIT_CUSTOMERS';

export const GET_OFFERS_SUCCESS = 'GET_OFFERS_SUCCESS';
export const OFFER_STATUS_SUCCESS = 'OFFER_STATUS_SUCCESS';
export const ADD_OFFERS_SUCCESS = 'ADD_OFFERS_SUCCESS';
export const EDIT_OFFERS_SUCCESS = 'EDIT_OFFERS_SUCCESS';
export const DELETE_OFFERS_SUCCESS = 'DELETE_OFFERS_SUCCESS';

export const GET_NOTICE_LIST_SUCCESS = 'GET_NOTICE_LIST_SUCCESS';

export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';

export const GET_REFERRAL_SUCCESS = 'GET_REFERRAL_SUCCESS';

export const GET_STATE_SUCCESS = 'GET_STATE_SUCCESS';
export const GET_CITY_SUCCESS = 'GET_CITY_SUCCESS';
export const ADD_LESSOR_SUCCESS = 'ADD_LESSOR_SUCCESS';
export const GET_LESSOR_ADDRESS_SUCCESS = 'GET_LESSOR_ADDRESS_SUCCESS';
export const ADD_LESSOR_ADDRESS_SUCCESS = 'ADD_LESSOR_ADDRESS_SUCCESS';
export const EDIT_LESSOR_ADDRESS_SUCCESS = 'EDIT_LESSOR_ADDRESS_SUCCESS';
export const GET_LESSOR_ADDRESS_BYID_SUCCESS = 'GET_LESSOR_ADDRESS_BYID_SUCCESS';
export const DELETE_LESSOR_ADDRESS_SUCCESS = 'DELETE_LESSOR_ADDRESS_SUCCESS';
export const GET_LESSOR_SUCCESS = 'GET_LESSOR_SUCCESS';
export const ADD_PREMISE_ADDRESS_SUCCESS = 'ADD_PREMISE_ADDRESS_SUCCESS';
export const EDIT_PREMISE_ADDRESS_SUCCESS = 'EDIT_PREMISE_ADDRESS_SUCCESS';
export const GET_PREMISE_ADDRESS_SUCCESS = 'GET_PREMISE_ADDRESS_SUCCESS';
export const DELETE_PREMISE_ADDRESS_SUCCESS = 'DELETE_PREMISE_ADDRESS_SUCCESS';
export const PROFILE_SETUP_SUCCESS = 'PROFILE_SETUP_SUCCESS';
export const FAQ_SUCCESS = 'FAQ_SUCCESS';
export const ABOUT_SUCCESS = 'ABOUT_SUCCESS';
export const TERMSOFUSE_SUCCESS = 'TERMSOFUSE_SUCCESS';
export const PRIVACYPOLICY_SUCCESS = 'PRIVACYPOLICY_SUCCESS';


