export const START_LOADER = 'START_LOADER';
export const STOP_LOADER = 'STOP_LOADER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SEARCH_TAXI_SUCCESS = 'SEARCH_TAXI_SUCCESS';
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const REGISTER_TAXI_SUCCESS = 'REGISTER_TAXI_SUCCESS';


